--CREATE TABLE CUSTOMERS(
	--ID int NOT NULL,
	--NAME varchar(20) NOT NULL,
	--AGE int NOT NULL,
	--SALARY int NOT NULL,
	--ADDRESS varchar(50),
	--PRIMARY KEY(ID))

	SELECT * FROM CUSTOMER

	INSERT INTO CUSTOMER VALUES (2,'WAHAJ',22,240000,'RasdR')

	DROP TABLE CUSTOMER 
	Where ID = 2

	SELECT * FROM CUSTOMERS 

	INSERT INTO CUSTOMERS VALUES (2,'WAHAJ',23,40000, 'sdfs')
	INSERT INTO CUSTOMERS VALUES (4,'SAM',22,45000, 'sTWfs')
	INSERT INTO CUSTOMERS VALUES (3,'SHAH',31,65000, 'sasdgfs')
	INSERT INTO CUSTOMERS VALUES (5,'HAMMAD',27,70000, 'sdfgfs')
	INSERT INTO CUSTOMERS VALUES (1,'AHSAN',24,20000, '')
	INSERT INTO CUSTOMERS VALUES (6,'SAMEER',29,50000, 'ssdf')

	SELECT * FROM CUSTOMERS
	ORDER BY ID

	UPDATE CUSTOMERS
	SET ID = 7
	Where ID =2

	UPDATE CUSTOMERS
	SET SALARY = SALARY * 1.25
	WHERE SALARY BETWEEN 20000 AND 45000

	DELETE FROM CUSTOMERS
	WHERE ID = 6

--	CREATE TABLE EMPLOYEES (   
--ID   INT              NOT NULL,   
--NAME VARCHAR (20)     NOT NULL,   
--AGE INT              NOT NULL,   
--ADDRESS CHAR (30),  
--SALARY   DECIMAL (18, 2),          
--PRIMARY KEY (ID));  

--SELECT * FROM EMPLOYEES

--INSERT INTO EMPLOYEES VALUES (1,'SHAIQ',29,'Lahore',54000)

--SELECT * FROM EMPLOYEES 



SELECT * FROM CUSTOMERS
INSERT INTO CUSTOMERS VALUES(10,'FAIQ',31,43000,'Khi')


CREATE TABLE ADMINS(
	ID int				NOT NULL,
	NAME varchar(20)	NOT NULL,
	AGE int				NOT NULL,
	ADDRESS varchar(30),
	PRIMARY KEY(ID))

	INSERT INTO ADMINS VALUES(1,'AZHAR',32)

