//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int employee_ID { get; set; }
        public string employeeName { get; set; }
        public string email { get; set; }
        public int age { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public Nullable<int> createdBy { get; set; }
        public Nullable<System.DateTime> updatedOn { get; set; }
        public Nullable<int> updatedBy { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public Nullable<int> FKDept_ID { get; set; }
    
        public virtual Department Department { get; set; }

        internal static object Where(Func<object, bool> p)
        {
            throw new NotImplementedException();
        }

        internal static void Remove(Employee empl)
        {
            throw new NotImplementedException();
        }

        internal static void Add(Employee emp)
        {
            throw new NotImplementedException();
        }
    }
}
