//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROLE
    {
        public int Role_ID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> createdOn { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> updatedOn { get; set; }
        public string updatedBy { get; set; }
        public byte isActive { get; set; }
        public byte isDeleted { get; set; }
        public Nullable<int> FKdept_ID { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
